### ISSUE TITLE
New directory is created with hardcoded permission

### ISSUE THREAD

**Issue by am0z** [z3ntu/atool#1]
https://github.com/z3ntu/atool/blob/f37b2c1ce03dd3ab144cd21bea861d061c2c29ac/atool#L1131

Quick backstory.  I have this problem that I wrote to the author but his email bounces.

Anyway I have a shared volume that several users use to aunpack and copy files.  Since atool creates new directories with 700 hardcoded it ignores specific filesystem permission I set using `setfact`.  I'm not sure if it's a bug or a feature.

I don't know why I'm creating this ticket here.  Archlinux still uses upstream from nongnu.org.  Have no idea how to get this potential fix there.

Cheers!

**Comment by z3ntu** [comment]
Hi, can you try if this works for you? https://github.com/z3ntu/atool/commit/a96792464ea4bf8a7d66f43eefd8be6cf7987fb6

Tbh I'm also bummed that original upstream is dead, so I'm maintaining this "fork" for myself, mostly for the zstd support.

**Comment by am0z** [comment]
Yep, this was easy to test.  Can confirm it fixes the issue I was having.
